apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: chatbot2-apr29-1
  janus-idp.io/tekton: chatbot2-apr29-1
  backstage.io/kubernetes-id: chatbot2-apr29-1
  backstage.io/kubernetes-namespace: chatbot2-apr29-1
  app.kubernetes.io/part-of: chatbot2-apr29-1
resources:
  - application-dev.yaml