kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot2-apr29-1-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: chatbot2-apr29-1-dsp-job
    namespace: chatbot2-apr29-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot2-apr29-1-dsp-job-role
